// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckIndexerConnection(arg1:main.DashboardSettings):Promise<main.IndexerStatusView>;

export function GetDashboardData():Promise<main.DashboardPayload>;

export function GetSettings():Promise<main.DashboardSettings>;

export function ReconnectAPI():Promise<main.DashboardPayload>;

export function SaveSettings(arg1:main.DashboardSettings):Promise<main.DashboardSettings>;

export function SendTransaction(arg1:main.SendTransactionRequest):Promise<main.SendTransactionResult>;

export function SetMiningEnabled(arg1:boolean):Promise<main.MiningControlResult>;

export function StartBackend(arg1:string):Promise<main.BackendLaunchResult>;
