// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckIndexerConnection(arg1) {
  return window['go']['main']['App']['CheckIndexerConnection'](arg1);
}

export function GetDashboardData() {
  return window['go']['main']['App']['GetDashboardData']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ReconnectAPI() {
  return window['go']['main']['App']['ReconnectAPI']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SendTransaction(arg1) {
  return window['go']['main']['App']['SendTransaction'](arg1);
}

export function SetMiningEnabled(arg1) {
  return window['go']['main']['App']['SetMiningEnabled'](arg1);
}

export function StartBackend(arg1) {
  return window['go']['main']['App']['StartBackend'](arg1);
}
